project_id = "cugunubcspfsgtwntics"

[functions.analyze-leads]
verify_jwt = false

[functions.kirvano-webhook]
verify_jwt = false

[functions.tiktok-capi]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-ai-reply]
verify_jwt = false

[functions.whatsapp-delayed-welcome]
verify_jwt = false